### ISSUE TITLE
使用学生身份可以免费注册微软开发者

### ISSUE THREAD

**Issue by xizhesun** [HDsky/zucc-student-resources#6]
请问，使用学生身份可以免费注册微软开发者，这个怎么搞？

**Comment by HDsky** [comment]
https://blog.csdn.net/luoyi000/article/details/84865970
以前是这样的，验证学生身份后，再去注册微软开发者可以用学生身份抵扣掉120元的注册费用。但现在的话可能改掉了

**Comment by HDsky** [comment]
https://www.weibo.com/ttarticle/p/show?id=2309404192539954563020

**Comment by HDsky** [comment]
现在好像没有了，我去更新下信息

**Comment by HDsky** [comment]
如果没有其他问题的话，这个issue就close了0.0
