### ISSUE TITLE
Jetbrains需人工审核

### ISSUE THREAD

**Issue by ShintaroTM** [HDsky/zucc-student-resources#7]
针对您日前提交的学生授权申请，我们必须核实您现在还是在校学生才能完成审查流程，并为您提供免费的JetBrains学生授权。

因人工审查的学生授权申请数量众多造成审查时辰拉长。为加速学生身份的审批流程和后续的处理、让您能够及早收到学生授权，即日起我们只接受以下补充材料来申请重新审批：

通过学信网获得的有效“在校学籍验证报告”，请下载PDF档案（含在线验证码）
这些补充材料的档案内容必须包含您的姓名、学校名称、学生证号码、日期、等等。
还请通过这个链接来提交补充信息： 您专用的平台入口链接

如果您有任何疑问，欢迎来信咨询。

**Comment by HDsky** [comment]
感谢～
